[build]
publish = "site/public"
command = "hugo --gc --minify -s site"

[context.production.environment]
HUGO_VERSION = "0.66"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo -s site"

[context.split1.environment]
HUGO_VERSION = "0.66"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL -s site"

[context.branch-deploy.environment]
HUGO_VERSION = "0.66"
