[build]
publish = "site/public"
command = "hugo -s site"

[context.production.environment]
HUGO_VERSION = "0.66.0/extended"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


[context.deploy-preview.environment]
HUGO_VERSION = "0.66.0/extended"
