baseURL: https://garancevallat.com
languageCode: en-us
title: Garance Vallat
theme: garance
# theme: ../..

########################################
######## Uncomment this option #########
########################################
# This options specify where to look for the images
assetDir: "assets"

# Option to specify the default language of the theme
# I.e., the landing language of your root
DefaultContentLanguage: en

## Option to disable additional language in your site.
# disableLanguages: ["ru"]

disableKinds: ["sitemap","RSS"]

# Option to specify that all links will be open in a new tab.
# blackfriday:
#  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parameter used to specify the number of article in each row
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 3

  # parameter used to specify if you want to minify the imported js
  jsMinify: true
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # option to specify the main colour of the theme
  mainColour: "#3F7797"

  # summary options
  summary:
    # option to specify the default image in the summary list
    # the starting folder is configure in "assetDir" of this file
    defaultImage : "/images/default_summary.jpg"

  # loading options
  loading:
    # option to specify the loading image
    # the starting folder is configure in "assetDir" of this file
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans"

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/owl.png"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the logo of the sidebar
    fontFamily: "Open Sans"

  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    # the starting folder is configure in "assetDir" of this file
    image: "/images/owl.png"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    # option to specify the title in the homepage
    title: Hi!
    # option to specify the subtitle in the homepage
    subtitle: I'm Garance, a software engineer in Barcelona, Spain, and you're on my site!
    # option to specify image in the homepage
    image: "/images/me.png" # worker.svg
    # option to specify the width of the image in the homepage
    imageWidth: 500px

  # footer options
  footer:
    # option to specify the logo in the footer
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/owl.png"
    # option to specify your contact email in the footer
    email:
      link: hola <a> garance.dev
      title: Send me an email
    # option to specify your linkedin profile in the footer
    linkedin:
      link: garance-vallat
      title: Find me on LinkedIn
    # option to specify your facebook account in the footer;
    # **uncomment** the lines below to show in footer
    # facebook:
    #   link: your.username
    #   title: Facebook
    # option to specify your github account in the footer;
    # **uncomment** the below lines to show in footer
    github:
      link: garancev
      title: My Github
    # option to specify your mastodon username in the footer;
    # **uncomment** the below lines to show in footer
    mastodon:
      link: garance
      title: Find me on Mastodon
    # option to specify your instagram username in the footer;
    # **uncomment** the below lines to show in footer
    # instagram:
    #    link: username
    #    title: Instagram
    # option to specify the copyright in the footer
    # copyright: Garance Vallat - 2020

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  en:
    languageName:       English
    weight:             1
