name = "Garance"
license = "MIT"
licenselink = "https://github.com/garancev/garance-web/blob/master/site/themes/garance/LICENSE"
description = ""
homepage = "https://garancevallat.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Garance"
  homepage = "https://garancevallat.com/"

# If porting an existing theme
[original]
  name = "Hugo refresh"
  homepage = "https://github.com/PippoRJ/hugo-refresh"
  repo = "https://github.com/PippoRJ/hugo-refresh"
